######################## default configuration ####################
baseURL = "https://www.bonnoces.com"
languageCode = "en-us"
title = "BonNoces | Kitchen And Household"
theme = "liva-hugo"
summaryLength = "10"
paginate = 6
disqusShortname = "BonNoces"

[outputs]
  home = ["HTML", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"

  
############################## navigation ###############################
[menu]
  
  # main menu
  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 1
  
  [[menu.main]]
  name = "Post"
  URL = "blog"
  weight = 2
  
  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 3

  # footer menu
  [[menu.footer]]
  name = "About"
  URL = "about"
  weight = 1
  
  [[menu.footer]]
  name = "Post"
  URL = "blog"
  weight = 2
  
  [[menu.footer]]
  name = "Contact"
  URL = "contact"
  weight = 3


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "BonNoces focus on household and kitchen products, and simplicity, aesthetic, colorfulness and environment protection are the philosophy BonNoces insists since its establishment."
author = "BonNoces"
# Google Analitycs
googleAnalitycsID = "UA-171528615-1"
# Contact Information
mobile = "8615360816675"
email = "service@bonnoces.com"
location = "china, Guangzhou"
# copyright
copyright = "| copyright &copy; 2020 [BonNoces](http://BonNoces.com) All Rights Reserved |"

  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = true

############################ news letter ########################
[params.newsletter]
enable = true
title = "Join Our Newsletter"
content = "Subscribe to get special offers, free giveaways, and once-in-a-lifetime deals."

############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "http://facebook.com/bonnoceskitchen"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/@BonNoces"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "http://instagram.com/bonnoces_kitchen"
